version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENER_INTERNAL: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAMES: INSIDE
      KAFKA_LISTENERS: INSIDE://kafka:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - "2181:2181"

  spark:
    image: bitnami/spark
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"

  airflow:
    image: apache/airflow
    environment:
      AIRFLOW_HOME: /opt/airflow
    ports:
      - "8081:8080"
